import type { VocabWord } from './vocabulary';

// Curated from the user's Cambridge A2 Flyers Flashcards PDF. These are teaching
// cards from Flyers material; some words also occur in earlier YLE levels.
export const flyersExtras: VocabWord[] = [
  { word: 'octopus', meaning: 'con bạch tuộc', level: 'flyers', topic: 'Con vật', emoji: '🐙', flyerSprite: 0 },
  { word: 'beetle', meaning: 'bọ cánh cứng', level: 'flyers', topic: 'Con vật', emoji: '🪲', flyerSprite: 1 },
  { word: 'dinosaur', meaning: 'khủng long', level: 'flyers', topic: 'Con vật', emoji: '🦖', flyerSprite: 2 },
  { word: 'swan', meaning: 'thiên nga', level: 'flyers', topic: 'Con vật', emoji: '🦢', flyerSprite: 3 },
  { word: 'tortoise', meaning: 'rùa cạn', level: 'flyers', topic: 'Con vật', emoji: '🐢', flyerSprite: 4 },
  { word: 'camel', meaning: 'lạc đà', level: 'flyers', topic: 'Con vật', emoji: '🐪', flyerSprite: 5 },
  { word: 'butterfly', meaning: 'con bướm', level: 'flyers', topic: 'Con vật', emoji: '🦋', flyerSprite: 6 },
  { word: 'eagle', meaning: 'đại bàng', level: 'flyers', topic: 'Con vật', emoji: '🦅', flyerSprite: 7 },
  { word: 'bandage', meaning: 'băng gạc', level: 'flyers', topic: 'Cơ thể & sức khỏe', emoji: '🩹', flyerSprite: 8 },
  { word: 'medicine', meaning: 'thuốc', level: 'flyers', topic: 'Cơ thể & sức khỏe', emoji: '💊', flyerSprite: 9 },
  { word: 'umbrella', meaning: 'chiếc ô', level: 'flyers', topic: 'Trang phục', emoji: '☂️', flyerSprite: 10 },
  { word: 'crown', meaning: 'vương miện', level: 'flyers', topic: 'Trang phục', emoji: '👑', flyerSprite: 11 },
  { word: 'glove', meaning: 'găng tay', level: 'flyers', topic: 'Trang phục', emoji: '🧤', flyerSprite: 12 },
  { word: 'necklace', meaning: 'vòng cổ', level: 'flyers', topic: 'Trang phục', emoji: '📿', flyerSprite: 13 },
  { word: 'pizza', meaning: 'bánh pizza', level: 'flyers', topic: 'Đồ ăn', emoji: '🍕', flyerSprite: 14 },
  { word: 'strawberry', meaning: 'quả dâu tây', level: 'flyers', topic: 'Đồ ăn', emoji: '🍓', flyerSprite: 15 },
  { word: 'honey', meaning: 'mật ong', level: 'flyers', topic: 'Đồ ăn', emoji: '🍯', flyerSprite: 16 },
  { word: 'olives', meaning: 'quả ô liu', level: 'flyers', topic: 'Đồ ăn', emoji: '🫒', flyerSprite: 17 },
  { word: 'fur', meaning: 'bộ lông thú', level: 'flyers', topic: 'Con vật', emoji: '🐾' },
  { word: 'insect', meaning: 'côn trùng', level: 'flyers', topic: 'Con vật', emoji: '🐞' },
  { word: 'nest', meaning: 'tổ chim', level: 'flyers', topic: 'Con vật', emoji: '🪺' },
  { word: 'extinct', meaning: 'tuyệt chủng', level: 'flyers', topic: 'Con vật', emoji: '🦕' },
  { word: 'elbow', meaning: 'khuỷu tay', level: 'flyers', topic: 'Cơ thể & sức khỏe', emoji: '💪' },
  { word: 'toe', meaning: 'ngón chân', level: 'flyers', topic: 'Cơ thể & sức khỏe', emoji: '🦶' },
  { word: 'finger', meaning: 'ngón tay', level: 'flyers', topic: 'Cơ thể & sức khỏe', emoji: '☝️' },
  { word: 'fall over', meaning: 'ngã', level: 'flyers', topic: 'Cơ thể & sức khỏe', emoji: '🤕' },
  { word: 'x-ray', meaning: 'ảnh X-quang', level: 'flyers', topic: 'Cơ thể & sức khỏe', emoji: '🩻' },
  { word: 'knee', meaning: 'đầu gối', level: 'flyers', topic: 'Cơ thể & sức khỏe', emoji: '🦵' },
  { word: "chemist's", meaning: 'hiệu thuốc', level: 'flyers', topic: 'Địa điểm', emoji: '🏥' },
  { word: 'pocket', meaning: 'túi áo hoặc quần', level: 'flyers', topic: 'Trang phục', emoji: '👖' },
  { word: 'trainers', meaning: 'giày thể thao', level: 'flyers', topic: 'Trang phục', emoji: '👟' },
  { word: 'pyjamas', meaning: 'đồ ngủ', level: 'flyers', topic: 'Trang phục', emoji: '🛌' },
  { word: 'bracelet', meaning: 'vòng tay', level: 'flyers', topic: 'Trang phục', emoji: '📿' },
  { word: 'belt', meaning: 'thắt lưng', level: 'flyers', topic: 'Trang phục', emoji: '👖' },
  { word: 'ring', meaning: 'chiếc nhẫn', level: 'flyers', topic: 'Trang phục', emoji: '💍' },
  { word: 'sunglasses', meaning: 'kính râm', level: 'flyers', topic: 'Trang phục', emoji: '🕶️' },
  { word: 'costume', meaning: 'trang phục hóa trang', level: 'flyers', topic: 'Trang phục', emoji: '🎭' },
  { word: 'salt', meaning: 'muối', level: 'flyers', topic: 'Đồ ăn', emoji: '🧂' },
  { word: 'jam', meaning: 'mứt', level: 'flyers', topic: 'Đồ ăn', emoji: '🍓' },
  { word: 'meal', meaning: 'bữa ăn', level: 'flyers', topic: 'Đồ ăn', emoji: '🍽️' },
  { word: 'fridge', meaning: 'tủ lạnh', level: 'flyers', topic: 'Nhà cửa', emoji: '🧊' },
  { word: 'pepper', meaning: 'hạt tiêu', level: 'flyers', topic: 'Đồ ăn', emoji: '🌶️' },
  { word: 'flour', meaning: 'bột mì', level: 'flyers', topic: 'Đồ ăn', emoji: '🌾' },
  { word: 'delicious', meaning: 'ngon', level: 'flyers', topic: 'Đồ ăn', emoji: '😋' },
  { word: 'cooker', meaning: 'bếp nấu', level: 'flyers', topic: 'Nhà cửa', emoji: '🍳' },
  { word: 'waiter', meaning: 'người phục vụ bàn', level: 'flyers', topic: 'Nghề nghiệp', emoji: '🧑‍🍳' },
  { word: 'chopsticks', meaning: 'đũa', level: 'flyers', topic: 'Đồ ăn', emoji: '🥢' },
  { word: 'butter', meaning: 'bơ', level: 'flyers', topic: 'Đồ ăn', emoji: '🧈' },
  { word: 'spoon', meaning: 'thìa', level: 'flyers', topic: 'Đồ ăn', emoji: '🥄' },
  { word: 'biscuit', meaning: 'bánh quy', level: 'flyers', topic: 'Đồ ăn', emoji: '🍪' },
  { word: 'knife', meaning: 'con dao', level: 'flyers', topic: 'Đồ ăn', emoji: '🔪' },
  { word: 'cereal', meaning: 'ngũ cốc ăn sáng', level: 'flyers', topic: 'Đồ ăn', emoji: '🥣' },
  { word: 'yoghurt', meaning: 'sữa chua', level: 'flyers', topic: 'Đồ ăn', emoji: '🥛' },
  { word: 'sugar', meaning: 'đường', level: 'flyers', topic: 'Đồ ăn', emoji: '🍬' },
  { word: 'fork', meaning: 'cái nĩa', level: 'flyers', topic: 'Đồ ăn', emoji: '🍴' },
  { word: 'oven', meaning: 'lò nướng', level: 'flyers', topic: 'Nhà cửa', emoji: '🍞' },
  { word: 'brush', meaning: 'bàn chải', level: 'flyers', topic: 'Nhà cửa', emoji: '🪥' },
  { word: 'shampoo', meaning: 'dầu gội', level: 'flyers', topic: 'Nhà cửa', emoji: '🧴' },
  { word: 'steps', meaning: 'các bậc thang', level: 'flyers', topic: 'Nhà cửa', emoji: '🪜' },
  { word: 'gate', meaning: 'cổng', level: 'flyers', topic: 'Nhà cửa', emoji: '🚪' },
  { word: 'shelf', meaning: 'cái kệ', level: 'flyers', topic: 'Nhà cửa', emoji: '📚' },
  { word: 'telephone', meaning: 'điện thoại', level: 'flyers', topic: 'Nhà cửa', emoji: '☎️' },
  { word: 'soap', meaning: 'xà phòng', level: 'flyers', topic: 'Nhà cửa', emoji: '🧼' },
  { word: 'metal', meaning: 'kim loại', level: 'flyers', topic: 'Vật liệu', emoji: '🔩' },
  { word: 'wood', meaning: 'gỗ', level: 'flyers', topic: 'Vật liệu', emoji: '🪵' },
  { word: 'stripes', meaning: 'các sọc', level: 'flyers', topic: 'Vật liệu', emoji: '🦓' },
  { word: 'glass', meaning: 'thủy tinh', level: 'flyers', topic: 'Vật liệu', emoji: '🥛' },
  { word: 'plastic', meaning: 'nhựa', level: 'flyers', topic: 'Vật liệu', emoji: '🧴' },
  { word: 'wool', meaning: 'len', level: 'flyers', topic: 'Vật liệu', emoji: '🧶' },
  { word: 'gold', meaning: 'vàng', level: 'flyers', topic: 'Vật liệu', emoji: '🥇' },
  { word: 'silver', meaning: 'bạc', level: 'flyers', topic: 'Vật liệu', emoji: '🥈' },
  { word: 'spots', meaning: 'các chấm bi', level: 'flyers', topic: 'Vật liệu', emoji: '🔵' },
  { word: 'factory', meaning: 'nhà máy', level: 'flyers', topic: 'Địa điểm', emoji: '🏭' },
  { word: 'bank', meaning: 'ngân hàng', level: 'flyers', topic: 'Địa điểm', emoji: '🏦' },
  { word: 'cave', meaning: 'hang động', level: 'flyers', topic: 'Địa điểm', emoji: '🕳️' },
  { word: 'fire station', meaning: 'trạm cứu hỏa', level: 'flyers', topic: 'Địa điểm', emoji: '🚒' },
  { word: 'bridge', meaning: 'cây cầu', level: 'flyers', topic: 'Địa điểm', emoji: '🌉' },
  { word: 'east', meaning: 'phía đông', level: 'flyers', topic: 'Địa điểm', emoji: '🧭' },
  { word: 'hotel', meaning: 'khách sạn', level: 'flyers', topic: 'Địa điểm', emoji: '🏨' },
  { word: 'north', meaning: 'phía bắc', level: 'flyers', topic: 'Địa điểm', emoji: '🧭' },
  { word: 'police station', meaning: 'đồn cảnh sát', level: 'flyers', topic: 'Địa điểm', emoji: '👮' },
  { word: 'stadium', meaning: 'sân vận động', level: 'flyers', topic: 'Địa điểm', emoji: '🏟️' },
  { word: 'west', meaning: 'phía tây', level: 'flyers', topic: 'Địa điểm', emoji: '🧭' },
  { word: 'post office', meaning: 'bưu điện', level: 'flyers', topic: 'Địa điểm', emoji: '📮' },
  { word: 'skyscraper', meaning: 'nhà chọc trời', level: 'flyers', topic: 'Địa điểm', emoji: '🏙️' },
  { word: 'straight on', meaning: 'đi thẳng', level: 'flyers', topic: 'Địa điểm', emoji: '⬆️' },
  { word: 'restaurant', meaning: 'nhà hàng', level: 'flyers', topic: 'Địa điểm', emoji: '🍴' },
  { word: 'south', meaning: 'phía nam', level: 'flyers', topic: 'Địa điểm', emoji: '🧭' },
  { word: 'theatre', meaning: 'nhà hát', level: 'flyers', topic: 'Địa điểm', emoji: '🎭' },
  { word: 'scissors', meaning: 'cái kéo', level: 'flyers', topic: 'Trường học', emoji: '✂️' },
  { word: 'timetable', meaning: 'thời khóa biểu', level: 'flyers', topic: 'Trường học', emoji: '📅' },
  { word: 'history', meaning: 'lịch sử', level: 'flyers', topic: 'Trường học', emoji: '📜' },
  { word: 'bin', meaning: 'thùng rác', level: 'flyers', topic: 'Trường học', emoji: '🗑️' },
  { word: 'backpack', meaning: 'ba lô', level: 'flyers', topic: 'Trường học', emoji: '🎒' },
  { word: 'glue', meaning: 'keo dán', level: 'flyers', topic: 'Trường học', emoji: '🧴' },
  { word: 'dictionary', meaning: 'từ điển', level: 'flyers', topic: 'Trường học', emoji: '📖' },
  { word: 'gym', meaning: 'phòng tập thể dục', level: 'flyers', topic: 'Trường học', emoji: '🏋️' },
  { word: 'magazine', meaning: 'tạp chí', level: 'flyers', topic: 'Giải trí', emoji: '📰' },
  { word: 'chess', meaning: 'cờ vua', level: 'flyers', topic: 'Giải trí', emoji: '♟️' },
  { word: 'skiing', meaning: 'trượt tuyết', level: 'flyers', topic: 'Giải trí', emoji: '⛷️' },
  { word: 'concert', meaning: 'buổi hòa nhạc', level: 'flyers', topic: 'Giải trí', emoji: '🎶' },
  { word: 'puzzle', meaning: 'trò ghép hình', level: 'flyers', topic: 'Giải trí', emoji: '🧩' },
  { word: 'swing', meaning: 'xích đu', level: 'flyers', topic: 'Giải trí', emoji: '🛝' },
  { word: 'snowboarding', meaning: 'trượt ván tuyết', level: 'flyers', topic: 'Giải trí', emoji: '🏂' },
  { word: 'prize', meaning: 'giải thưởng', level: 'flyers', topic: 'Giải trí', emoji: '🏆' },
  { word: 'race', meaning: 'cuộc đua', level: 'flyers', topic: 'Giải trí', emoji: '🏁' },
  { word: 'winner', meaning: 'người chiến thắng', level: 'flyers', topic: 'Giải trí', emoji: '🥇' },
  { word: 'suitcase', meaning: 'vali', level: 'flyers', topic: 'Đi lại', emoji: '🧳' },
  { word: 'calendar', meaning: 'tờ lịch', level: 'flyers', topic: 'Thời gian', emoji: '🗓️' },
  { word: 'midnight', meaning: 'nửa đêm', level: 'flyers', topic: 'Thời gian', emoji: '🌙' },
  { word: 'midday', meaning: 'giữa trưa', level: 'flyers', topic: 'Thời gian', emoji: '☀️' },
  { word: 'ambulance', meaning: 'xe cứu thương', level: 'flyers', topic: 'Đi lại', emoji: '🚑' },
  { word: 'motorway', meaning: 'đường cao tốc', level: 'flyers', topic: 'Đi lại', emoji: '🛣️' },
  { word: 'wheel', meaning: 'bánh xe', level: 'flyers', topic: 'Đi lại', emoji: '🛞' },
  { word: 'traffic', meaning: 'giao thông', level: 'flyers', topic: 'Đi lại', emoji: '🚦' },
  { word: 'rocket', meaning: 'tên lửa', level: 'flyers', topic: 'Đi lại', emoji: '🚀' },
  { word: 'taxi', meaning: 'xe taxi', level: 'flyers', topic: 'Đi lại', emoji: '🚕' },
  { word: 'fire engine', meaning: 'xe cứu hỏa', level: 'flyers', topic: 'Đi lại', emoji: '🚒' },
  { word: 'platform', meaning: 'sân ga', level: 'flyers', topic: 'Đi lại', emoji: '🚉' },
  { word: 'spaceship', meaning: 'tàu vũ trụ', level: 'flyers', topic: 'Đi lại', emoji: '🛸' },
  { word: 'tour', meaning: 'chuyến tham quan', level: 'flyers', topic: 'Đi lại', emoji: '🧳' },
  { word: 'actor', meaning: 'diễn viên', level: 'flyers', topic: 'Nghề nghiệp', emoji: '🎭' },
  { word: 'office', meaning: 'văn phòng', level: 'flyers', topic: 'Nghề nghiệp', emoji: '🏢' },
  { word: 'fire fighter', meaning: 'lính cứu hỏa', level: 'flyers', topic: 'Nghề nghiệp', emoji: '🧑‍🚒' },
  { word: 'police officer', meaning: 'cảnh sát', level: 'flyers', topic: 'Nghề nghiệp', emoji: '👮' },
  { word: 'photographer', meaning: 'nhiếp ảnh gia', level: 'flyers', topic: 'Nghề nghiệp', emoji: '📷' },
  { word: 'businessman', meaning: 'doanh nhân', level: 'flyers', topic: 'Nghề nghiệp', emoji: '💼' },
  { word: 'journalist', meaning: 'nhà báo', level: 'flyers', topic: 'Nghề nghiệp', emoji: '📰' },
  { word: 'singer', meaning: 'ca sĩ', level: 'flyers', topic: 'Nghề nghiệp', emoji: '🎤' },
  { word: 'pilot', meaning: 'phi công', level: 'flyers', topic: 'Nghề nghiệp', emoji: '🧑‍✈️' },
];
